[package]
name = "ctf_chal_creator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
curl = "0.4.38"
colored = "2.0.0"